#Serverless Documentation: https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/

service: go

provider:
  name: aws
  runtime: go1.x
  region: sa-east-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: /
          method: get
          cors: true